name: Test
on: [push, pull_request]
jobs:
  linux-lts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: lts/*
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
  linux-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: node
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
  linux-exact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: "10.0.0"
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
        if [ $(node -v) != "v10.0.0" ]; then
          exit 1;
        fi
  linux-nvmrc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
        if [ $(node -v) != "v12.9.0" ]; then
          exit 1;
        fi
  linux-canary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: node
        node-mirror: https://nodejs.org/download/v8-canary/
    - name: Check
      run: |
        which node
        node -v
        which npm
        npm -v
  windows-lts:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: lts/*
    - name: Check
      run: |
        node -v
        npm -v
  windows-stable:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: node
    - name: Check
      run: |
        node -v
        npm -v
  windows-exact:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: "10.0.0"
    - name: Check
      run: |
        node -v
        npm -v
  windows-nvmrc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
    - name: Check
      run: |
        node -v
        npm -v
  windows-canary:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: node
        node-mirror: https://nodejs.org/download/v8-canary/
    - name: Check
      run: |
        node -v
        npm -v
  macos-lts:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: lts/*
    - name: Check
      run: |
        node -v
        npm -v
  macos-stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: node
    - name: Check
      run: |
        node -v
        npm -v
  macos-exact:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        node-version: "10.0.0"
    - name: Check
      run: |
        node -v
        npm -v
  macos-nvmrc:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
    - name: Check
      run: |
        node -v
        npm -v
  macos-canary:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
        node-version: node
        node-mirror: https://nodejs.org/download/v8-canary/
    - name: Check
      run: |
        node -v
        npm -v
